export const teddyBears = [
  {
    id: '1',
    name: 'Gấu Teddy Classic',
    price: 299000,
    description: 'Gấu bông Teddy cổ điển với chất liệu lông mềm mại, kích thước 30cm',
    image: require('../assets/images/teddy1.jpg'),
    category: 'Classic',
    rating: 4.5,
    reviews: 128,
    inStock: true,
  },
  {
    id: '2',
    name: 'Gấu Teddy Màu Hồng',
    price: 349000,
    description: 'Gấu bông Teddy màu hồng ngọt ngào, kích thước 35cm',
    image: require('../assets/images/teddy2.jpg'),
    category: 'Colorful',
    rating: 4.8,
    reviews: 95,
    inStock: true,
  },
  {
    id: '3',
    name: 'Gấu Teddy Khổng Lồ',
    price: 599000,
    description: 'Gấu bông Teddy kích thước lớn 80cm, hoàn hảo để ôm',
    image: require('../assets/images/teddy3.jpg'),
    category: 'Giant',
    rating: 4.9,
    reviews: 156,
    inStock: true,
  },
  {
    id: '4',
    name: 'Gấu Teddy Mini',
    price: 199000,
    description: 'Gấu bông Teddy kích thước nhỏ 20cm, dễ thương',
    image: require('../assets/images/teddy4.jpg'),
    category: 'Mini',
    rating: 4.3,
    reviews: 87,
    inStock: true,
  },
  {
    id: '5',
    name: 'Gấu Teddy Đặc Biệt',
    price: 449000,
    description: 'Gấu bông Teddy phiên bản đặc biệt với quần áo thời trang',
    image: require('../assets/images/teddy5.jpg'),
    category: 'Special',
    rating: 4.7,
    reviews: 112,
    inStock: true,
  },
]; 